#cloud-config
ssh_authorized_keys:
  - "${ssh_public_key}"
coreos:
  locksmith:
  update:
    reboot-strategy: "${reboot_strategy}"
  units:
    - name: set-timezone.service
      enable: true
      content: |
        [Unit]
        Description=Set the time zone
        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone UTC
        RemainAfterExit=yes
        Type=oneshot
        [Install]
        WantedBy=multi-user.target
    - name: networkd-restart.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=Restart systemd-networkd to be sure we are using correct network settings
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/bash -c 'systemctl restart systemd-networkd'
write_files:
  - path: /etc/vpm/config.yaml
    permissions: 0644
    owner: root
    encoding: b64
    content: ${vp_manager_config}
  - path: /etc/systemd/resolved.conf
    permissions: 0644
    owner: root
    content: |
      [Resolve]
      DNS=1.1.1.1
  - path: /etc/systemd/chronyd.conf
    permissions: 0420
    owner: root
    content: |
      pool ${ntp_servers} iburst
      driftfile /var/lib/chrony/drift
      makestep 0.1 3
      rtcsync
bootcmd:
  - sed -i '/vip/d' /etc/hosts
  - for h in `host ${nlb_dns_name}|awk '{print $4}'`; do ping -c1 -W1 $h; grep $h /proc/net/arp|cut -d' ' -f1|xargs -r printf -- "%s vip\n" >>/etc/hosts; done

