apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${cluster_name}-${host_name}
  creationTimestamp: null
spec:
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
      labels:
        cluster: ${cluster_name}
    spec:
      domain:
        cpu:
          model: host-passthrough
        resources:
          limits:
            cpu: 8
            memory: 64Gi
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: cloudinit
            disk:
              bus: virtio
          interfaces:
            - sriov: {}
              name: default-net
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
      networks:
      - name: default-net
        multus:
          networkName: ${network}
      volumes:
        - name: containerdisk
          containerDisk:
            image: ${f5xc_rhel9_container}
        - name: cloudinit
          cloudInitNoCloud:
            networkData: |
              version: 1
              config:
                - type: physical
                  name: eth0
                  subnets:
                    - type: static
                      address: ${ip_address}
                      gateway: ${ip_gateway}
                      dns_nameservers:
                        - 8.8.8.8
            userData: |
              #cloud-config
              users:
                - name: "vesop"
                  passwd: ""
                  groups:
                    - "sudo"
              coreos:
                update:
                  reboot-strategy: "off"
              network:
                version: 2
              write_files:
              - path: /etc/vpm/config.yaml
                permissions: 0644
                owner: root
                content: |
                  Kubernetes:
                    EtcdUseTLS: true
                    Server: vip
                  Vpm:
                    ClusterName: ${cluster_name}
                    ClusterType: ce
                    Config: /etc/vpm/config.yaml
                    Labels:
                      testbed: make-me-a-var
                    Hostname: ${cluster_name}-${host_name}
                    StaticIpConfiguration:
                      SiteLocalIp: ${ip_address}
                      SiteLocalGw: ${ip_gateway}
                      DnsServers:
                      - 8.8.8.8
                    Latitude: ${latitude}
                    Longitude: ${longitude}
                    MauriceEndpoint: ${maurice_endpoint}
                    MauricePrivateEndpoint: ${maurice_private_endpoint}
                    Proxy: {}
                    EnableIpv6: true
                    Token: ${site_registration_token}
              - path: /etc/vpm/certified-hardware.yaml
                permissions: 0644
                owner: root
                content: |
                  active: ${certified_hardware_profile}
                  certifiedHardware:
                    kvm-voltstack-combo:
                      Vpm:
                        PrivateNIC: eth0
                      outsideNic:
                      - eth0
                    kvm-regular-nic-voltmesh:
                      Vpm:
                        PrivateNIC: eth0
                      outsideNic:
                      - eth0
                    ${certified_hardware_profile}:
                      Vpm:
                        PrivateNIC: eth0
                      outsiteNic:
                      - eth0
                  primaryOutsideNic: eth0
              runcmd:
                - [ sh, -c, test -e /usr/bin/fsextend  && /usr/bin/fsextend || true ]
              hostname: ${cluster_name}-${host_name}
